{{- if and .Values.cloudflared.enabled .Values.cloudflared.token (not .Values.cloudflared.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: ll-cloudflared-token
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloudflared
    {{- include "ll-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.cloudflared.token | quote }}
{{- end }}
